### ISSUE TITLE
Auto complete call of procedures

### ISSUE THREAD

**Issue by agch-dev** [bryant1410/Sublime-Text-3-Modula-2-Syntax#3]
It would be great if when calling a procedure, when you are writing the part where you call it, It auto completed all but the name of the variables that you are going to send to the procedure, instead of just the name of the procedure.

For example if I have:

PROCEDURE hello (x, y: INTEGER; p: Tperson)
 code..
END hello;

then if I start typing : hel.. The autocomplete is going to suggest me
hello ( | , ,  ); with the cursor being " | ".

BTW love your pluggin it saves a lot of time

**Comment by bryant1410** [comment]
thanks :sweat_smile:

**Comment by agch-dev** [comment]
Nuuuuu sos el profe de practico jaja, recien me doy cuenta. Gracias por la ayuda.

**Comment by bryant1410** [comment]
jaja No hay problema :smile:
